import ProductAPI from "../services/productAPI.js";
import Validation from "../model/Validation.js";
const api=new ProductAPI(),validation=new Validation();let products=[],editingId=null;
const $=id=>document.getElementById(id),money=v=>Number(v).toLocaleString("vi-VN")+" ₫";
const form=$("productForm"),tbody=$("productTableBody");
function toast(msg,type="success"){const el=$("appToast");$("toastBody").textContent=msg;el.classList.remove("text-bg-success","text-bg-danger");el.classList.add(type==="danger"?"text-bg-danger":"text-bg-success");bootstrap.Toast.getOrCreateInstance(el).show()}
function data(){return{name:$("productName").value.trim(),price:Number($("productPrice").value),type:$("productType").value,img:$("productImage").value.trim(),screen:$("productScreen").value.trim(),backCamera:$("productBackCamera").value.trim(),frontCamera:$("productFrontCamera").value.trim(),desc:$("productDesc").value.trim()}}
function errorsClear(){document.querySelectorAll(".validation-message").forEach(x=>x.textContent="")}
function errorsShow(e){errorsClear();Object.entries(e).forEach(([k,v])=>{const el=$("error"+k.charAt(0).toUpperCase()+k.slice(1));if(el)el.textContent=v})}
function stats(){
 $("totalProducts").textContent=products.length;$("samsungCount").textContent=products.filter(x=>String(x.type).toLowerCase()==="samsung").length;$("iphoneCount").textContent=products.filter(x=>String(x.type).toLowerCase()==="iphone").length;
}
function render(list=products){if(!list.length){tbody.innerHTML='<tr><td colspan="7" class="text-center py-5">Không có sản phẩm.</td></tr>';stats();return}tbody.innerHTML=list.map(p=>`<tr><td>${p.id}</td><td><img class="admin-product-img" src="${p.img||'https://placehold.co/80x80?text=Phone'}" alt="${p.name}"></td><td class="fw-semibold">${p.name}</td><td>${p.type}</td><td class="text-danger fw-bold">${money(p.price)}</td><td>${p.desc||"-"}</td><td><button class="btn btn-sm btn-outline-primary btnEdit" data-id="${p.id}"><i class="fa-solid fa-pen"></i></button> <button class="btn btn-sm btn-outline-danger btnDelete" data-id="${p.id}"><i class="fa-solid fa-trash"></i></button></td></tr>`).join("");stats()}
function apply(){const q=$("searchName").value.toLowerCase().trim();let a=products.filter(p=>String(p.name).toLowerCase().includes(q));if($("sortPrice").value==="asc")a.sort((x,y)=>x.price-y.price);if($("sortPrice").value==="desc")a.sort((x,y)=>y.price-x.price);render(a)}
function reset(){form.reset();errorsClear();editingId=null;$("modalTitle").textContent="Thêm sản phẩm";$("btnSaveProduct").textContent="Thêm sản phẩm"}
function fill(p){$("productName").value=p.name||"";$("productPrice").value=p.price||"";$("productType").value=p.type||"";$("productImage").value=p.img||"";$("productScreen").value=p.screen||"";$("productBackCamera").value=p.backCamera||"";$("productFrontCamera").value=p.frontCamera||"";$("productDesc").value=p.desc||""}
async function load(){try{products=await api.getAll();render()}catch(e){console.error(e);tbody.innerHTML='<tr><td colspan="7"><div class="alert alert-danger m-3">Không thể kết nối API.</div></td></tr>'}}
form.addEventListener("submit",async e=>{e.preventDefault();const d=data(),er=validation.validateProduct(d);if(Object.keys(er).length)return errorsShow(er);try{if(editingId===null){await api.create(d);toast("Thêm sản phẩm thành công.")}else{await api.update(editingId,d);toast("Cập nhật sản phẩm thành công.")}await load();bootstrap.Modal.getOrCreateInstance($("productModal")).hide();reset()}catch(err){console.error(err);toast("Thao tác API thất bại.","danger")}});
tbody.addEventListener("click",async e=>{const ed=e.target.closest(".btnEdit"),del=e.target.closest(".btnDelete");if(ed){const p=products.find(x=>String(x.id)===String(ed.dataset.id));if(!p)return;editingId=p.id;$("modalTitle").textContent="Cập nhật sản phẩm";$("btnSaveProduct").textContent="Lưu thay đổi";fill(p);errorsClear();bootstrap.Modal.getOrCreateInstance($("productModal")).show()}if(del){if(!confirm("Bạn có chắc muốn xóa sản phẩm này?"))return;try{await api.delete(del.dataset.id);toast("Xóa sản phẩm thành công.");await load()}catch(err){toast("Xóa sản phẩm thất bại.","danger")}}});
$("btnOpenAdd").addEventListener("click",reset);$("searchName").addEventListener("input",apply);$("sortPrice").addEventListener("change",apply);$("btnResetFilter").addEventListener("click",()=>{$("searchName").value="";$("sortPrice").value="";render()});load();
